name: CI/CD Pipeline for 3-Tier App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend image
      run: |
        docker build -t yuvaraju/frontend:latest frontend/
        docker push yuvaraju/frontend:latest

    - name: Build and push backend image
      run: |
        docker build -t yuvaraju/backend:latest backend/
        docker push yuvaraju/backend:latest

    - name: Set up kubeconfig directory
      run: mkdir -p ~/.kube

    - name: Set up kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_EKS }}" > ~/.kube/config
        export KUBECONFIG=~/.kube/config

    - name: Set permissions on kubeconfig
      run: chmod 600 ~/.kube/config

    - name: Tail kubeconfig
      run: tail ~/.kube/config
      
    - name: Verify Kubernetes connection
      run: kubectl get -all
    
    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        kubectl apply -f frontend-deployment.yaml
        kubectl apply -f backend-deployment.yaml
        kubectl apply -f database-deployment.yaml